#ifndef SPIFLASHMEM_DRIVER_
#define SPIFLASHMEM_DRIVER_

/* TODO: finish porting */
#define ENABLE_CHIP
#define READSTATUS1REG_INSTRUCTION
#define DISABLE_CHIP
#define READUNIQUEID_INSTRUCTION
#define GETJDECID_INSTRUCTION
#define WRITEDISABLE_INSTRUCTION
#define ERASECHIP_INSTRUCTION
#define WRITEENABLE_INSTRUCTION
#define POWERDOWN_INSTRUCTION
#define POWERUP_INSTRUCTION
#define FASTREAD_INSTRUCTION
#define READDATA_INSTRUCTION
#define WRITEDATA_INSTRUCTION
#define ERASESECTOR_INSTRUCTION
#define BLOCKERASE32KB_INSTRUCTION
#define BLOCKERASE64KB_INSTRUCTION


#define LASTFLASH_MEMADDR 255

#endif /* SPIFLASHMEM_DRIVER_ */
